//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string active {
            get {
                return ResourceManager.GetString("active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Store.
        /// </summary>
        internal static string addStore {
            get {
                return ResourceManager.GetString("addStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Sub Property.
        /// </summary>
        internal static string addSubProperty {
            get {
                return ResourceManager.GetString("addSubProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement Doc No.
        /// </summary>
        internal static string agreementDocNo {
            get {
                return ResourceManager.GetString("agreementDocNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement Type.
        /// </summary>
        internal static string agreementType {
            get {
                return ResourceManager.GetString("agreementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert List.
        /// </summary>
        internal static string alertList {
            get {
                return ResourceManager.GetString("alertList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CJ Express.
        /// </summary>
        internal static string appName {
            get {
                return ResourceManager.GetString("appName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve User.
        /// </summary>
        internal static string approveUser {
            get {
                return ResourceManager.GetString("approveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Type.
        /// </summary>
        internal static string assetType {
            get {
                return ResourceManager.GetString("assetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string changePassword {
            get {
                return ResourceManager.GetString("changePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บริษัท ซีเจ เอ็กเพรส กรุ๊ป จํากัด.
        /// </summary>
        internal static string companyName {
            get {
                return ResourceManager.GetString("companyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition Expire Date.
        /// </summary>
        internal static string conditionExpireDate {
            get {
                return ResourceManager.GetString("conditionExpireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string confirmpassword {
            get {
                return ResourceManager.GetString("confirmpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm turn off alert {0} item{1}.
        /// </summary>
        internal static string confirmTurnOffAlert {
            get {
                return ResourceManager.GetString("confirmTurnOffAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Turn Of Alert Selection.
        /// </summary>
        internal static string confirmTurnOffAlertModalTitle {
            get {
                return ResourceManager.GetString("confirmTurnOffAlertModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Center.
        /// </summary>
        internal static string costCenter {
            get {
                return ResourceManager.GetString("costCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Property.
        /// </summary>
        internal static string createproperty {
            get {
                return ResourceManager.GetString("createproperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Sub Property.
        /// </summary>
        internal static string deleteSubProperty {
            get {
                return ResourceManager.GetString("deleteSubProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doc.
        /// </summary>
        internal static string doc {
            get {
                return ResourceManager.GetString("doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Date.
        /// </summary>
        internal static string docEffectiveDate {
            get {
                return ResourceManager.GetString("docEffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire Date.
        /// </summary>
        internal static string docExpireDate {
            get {
                return ResourceManager.GetString("docExpireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doc Run No.
        /// </summary>
        internal static string docRunNo {
            get {
                return ResourceManager.GetString("docRunNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        internal static string document {
            get {
                return ResourceManager.GetString("document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string download {
            get {
                return ResourceManager.GetString("download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download All.
        /// </summary>
        internal static string downloadAll {
            get {
                return ResourceManager.GetString("downloadAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Property.
        /// </summary>
        internal static string editProperty {
            get {
                return ResourceManager.GetString("editProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Sub Property.
        /// </summary>
        internal static string editSubProperty {
            get {
                return ResourceManager.GetString("editSubProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine No..
        /// </summary>
        internal static string engineNo {
            get {
                return ResourceManager.GetString("engineNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee Amount.
        /// </summary>
        internal static string feeAmount {
            get {
                return ResourceManager.GetString("feeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Document.
        /// </summary>
        internal static string filterDocument {
            get {
                return ResourceManager.GetString("filterDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Store.
        /// </summary>
        internal static string filterStore {
            get {
                return ResourceManager.GetString("filterStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter User.
        /// </summary>
        internal static string filterUser {
            get {
                return ResourceManager.GetString("filterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter User Class.
        /// </summary>
        internal static string filterUserClass {
            get {
                return ResourceManager.GetString("filterUserClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string inactive {
            get {
                return ResourceManager.GetString("inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lessee Vendor Name.
        /// </summary>
        internal static string lesseeVendorName {
            get {
                return ResourceManager.GetString("lesseeVendorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Doc No.
        /// </summary>
        internal static string licenseDocNo {
            get {
                return ResourceManager.GetString("licenseDocNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License End Date.
        /// </summary>
        internal static string licenseEndDate {
            get {
                return ResourceManager.GetString("licenseEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Renew Date.
        /// </summary>
        internal static string licenseRenewDate {
            get {
                return ResourceManager.GetString("licenseRenewDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Type.
        /// </summary>
        internal static string licenseType {
            get {
                return ResourceManager.GetString("licenseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (EN).
        /// </summary>
        internal static string nameEN {
            get {
                return ResourceManager.GetString("nameEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (TH).
        /// </summary>
        internal static string nameTH {
            get {
                return ResourceManager.GetString("nameTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string newPassword {
            get {
                return ResourceManager.GetString("newPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice Date.
        /// </summary>
        internal static string noticeDate {
            get {
                return ResourceManager.GetString("noticeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        internal static string oldPassword {
            get {
                return ResourceManager.GetString("oldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select.
        /// </summary>
        internal static string pleaseSelect {
            get {
                return ResourceManager.GetString("pleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties In System.
        /// </summary>
        internal static string propertiesinsystem {
            get {
                return ResourceManager.GetString("propertiesinsystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Description (EN).
        /// </summary>
        internal static string propertydesc_en {
            get {
                return ResourceManager.GetString("propertydesc_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Description (TH).
        /// </summary>
        internal static string propertydesc_th {
            get {
                return ResourceManager.GetString("propertydesc_th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Name.
        /// </summary>
        internal static string propertyname {
            get {
                return ResourceManager.GetString("propertyname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Code.
        /// </summary>
        internal static string property_code {
            get {
                return ResourceManager.GetString("property_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        internal static string province {
            get {
                return ResourceManager.GetString("province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Doc.
        /// </summary>
        internal static string resultDoc {
            get {
                return ResourceManager.GetString("resultDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results for &quot;Store&quot;.
        /// </summary>
        internal static string resultStore {
            get {
                return ResourceManager.GetString("resultStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results for &quot;User&quot;.
        /// </summary>
        internal static string resultUser {
            get {
                return ResourceManager.GetString("resultUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results for &quot;User Class&quot;.
        /// </summary>
        internal static string resultUserClass {
            get {
                return ResourceManager.GetString("resultUserClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select status.
        /// </summary>
        internal static string selectStatus {
            get {
                return ResourceManager.GetString("selectStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space Rental Conditional Expire Date.
        /// </summary>
        internal static string spaceRentalConditionExpireDate {
            get {
                return ResourceManager.GetString("spaceRentalConditionExpireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doc No.
        /// </summary>
        internal static string spaceRentalDocNo {
            get {
                return ResourceManager.GetString("spaceRentalDocNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space Rental Type.
        /// </summary>
        internal static string spaceRentalType {
            get {
                return ResourceManager.GetString("spaceRentalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify paid date.
        /// </summary>
        internal static string specifyPaidDate {
            get {
                return ResourceManager.GetString("specifyPaidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start-End Date.
        /// </summary>
        internal static string startEndDate {
            get {
                return ResourceManager.GetString("startEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        internal static string store {
            get {
                return ResourceManager.GetString("store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Code.
        /// </summary>
        internal static string storeCode {
            get {
                return ResourceManager.GetString("storeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Name.
        /// </summary>
        internal static string storeName {
            get {
                return ResourceManager.GetString("storeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Name (EN).
        /// </summary>
        internal static string storeNameEN {
            get {
                return ResourceManager.GetString("storeNameEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Name (TH).
        /// </summary>
        internal static string storeNameTH {
            get {
                return ResourceManager.GetString("storeNameTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string submit {
            get {
                return ResourceManager.GetString("submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Property Description (EN).
        /// </summary>
        internal static string subPropertyDesc_EN {
            get {
                return ResourceManager.GetString("subPropertyDesc_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Property Description (TH).
        /// </summary>
        internal static string subPropertyDesc_TH {
            get {
                return ResourceManager.GetString("subPropertyDesc_TH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Property Name.
        /// </summary>
        internal static string subPropertyName {
            get {
                return ResourceManager.GetString("subPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        internal static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname (EN).
        /// </summary>
        internal static string surnameEN {
            get {
                return ResourceManager.GetString("surnameEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname (TH).
        /// </summary>
        internal static string surnameTH {
            get {
                return ResourceManager.GetString("surnameTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Off Alert.
        /// </summary>
        internal static string turnOffAlert {
            get {
                return ResourceManager.GetString("turnOffAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Date.
        /// </summary>
        internal static string updateDate {
            get {
                return ResourceManager.GetString("updateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Store.
        /// </summary>
        internal static string updateStore {
            get {
                return ResourceManager.GetString("updateStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update User.
        /// </summary>
        internal static string updateUser {
            get {
                return ResourceManager.GetString("updateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Class.
        /// </summary>
        internal static string userClass {
            get {
                return ResourceManager.GetString("userClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Request Id.
        /// </summary>
        internal static string userRequestId {
            get {
                return ResourceManager.GetString("userRequestId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Verify Id.
        /// </summary>
        internal static string userVerifyId {
            get {
                return ResourceManager.GetString("userVerifyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle License No..
        /// </summary>
        internal static string vehicleLicense {
            get {
                return ResourceManager.GetString("vehicleLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Model.
        /// </summary>
        internal static string vehicleModel {
            get {
                return ResourceManager.GetString("vehicleModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doc No..
        /// </summary>
        internal static string vehicleRentalDocNo {
            get {
                return ResourceManager.GetString("vehicleRentalDocNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Name.
        /// </summary>
        internal static string vendorName {
            get {
                return ResourceManager.GetString("vendorName", resourceCulture);
            }
        }
    }
}
